### ISSUE TITLE
.spacemacs vs. blog post

### ISSUE THREAD

**Issue by rhaynes74** [benswift/.dotfiles#1]
Good day sir - I have been reading about your org-roam-bibtex config.  I notice that your complete .spacemacs file looks quite a bit different that the pieces provided in your blog post.  Which one should be followed?

**Comment by benswift** [comment]
Hey there, I must confess that I haven't been using the org-roam-bibtex stuff recently (I still use org mode a lot, but not the roam stuff). It's quite possible that my hacks to get it all working have been superseded by recent changes to spacemacs and/or org-roam-bibtex.

Having said that, the stuff in `.spacemacs` is more likely to work than what's in the blog post. So I'd start there.
